### PR TITLE
Updated arduino stm32 package version

### PR DESCRIPTION
**Pull request by ubis**

### CODE REVIEW

**Comment by ivankravets** [comment]
Please take a look at my latest commit https://github.com/platformio/platform-ststm32/commit/3f6dbd1b74524d415cc2269f2866b3beb5655c11

Do you have any comments/corrections?

**Comment by ubis** [comment]
Yeah, I'm looking at it now. Everything seems to be ok. Although you didn't added that "maple bootloader revision change through platformio.ini...." and I closed my PR due some conflicts. 

Well, either you will add it or I will sooner or later. Overall seems to be okay.
Also I noticed, that you changed/uploaded framework-ststm32 to your servers, so I will close this PR.

**Comment by ivankravets** [comment]
>  Although you didn't added that "maple bootloader revision change through platformio.ini...." and I closed my PR due some conflicts.

Please sorry, I forgot. What I should add?

**Comment by ivankravets** [comment]
> Also I noticed, that you changed/uploaded framework-ststm32 to your servers, so I will close this PR.

Yes, I removed all tools from frameworks and pack only sources. Please ping me when need to update this framework. Need to think how to automate these things.

**Comment by ubis** [comment]
> Please sorry, I forgot. What I should add?

It's okay. But if you still want to add it, well... Maple bootloader revision should be either 1 or 2(newer).
It should be available to change in platformio.ini;
That revision is used only in one place - dfu uploader parameters. Note: [main.py](https://github.com/platformio/platform-ststm32/blob/develop/builder/main.py) 146 line: 
`_upload_flags = ["2", "%s:%s" % (_usbids[0][0][2:], _usbids[0][1][2:])]`

That first: '2' parameter is bootloader revision, so it should be either 1 or 2.

> Please ping me when need to update this framework. Need to think how to automate these things.

Sure thing ;)
Perhaps somekind of build server(which would clone repo when there is any changes and remove unnecesary files, like upload tools in this case)?

**Comment by ivankravets** [comment]
Are you sure that Serial protocol should be used by default? I've just installed Arduino IDE & STM32Duino and they use DFU by default.

**Comment by ubis** [comment]
@ivankravets serial bootloader is installed by manufacturer. Unless you got a board with pre-installed maple(dfu) bootloader. But, seeing that many people uses dfu, it could be used as default aswell.

**Comment by ivankravets** [comment]
Should we use all DFU by default?

**Comment by ubis** [comment]
Yeah, I guess it can be used for all boards.

**Comment by ivankravets** [comment]
Thanks! Let's wait for the answer for this https://github.com/platformio/platform-ststm32/issues/9#issuecomment-253495163

**Pull request closed without merging**
