### PR TITLE
Added and tested cmsis for Bluepill_f103c8.

### PR DESCRIPTION
**Pull request by m-chichikalov**
Yep, not a big deal, however cmsis available for bluepill_f103 now.

I'm gonna add SPL for f1's seria a bit later...

success compillation bluepill_f103 by platformio

### CODE REVIEW

**Comment by m-chichikalov** [comment]
Strange, Travis could not build example...

**Comment by m-chichikalov** [comment]
Looks like Travis cannot find stm32f103c8.ld
 but I didn't face this problem during testing.

**Comment by guedou** [comment]
Any update on this PR? I would like to use this feature.

**Comment by guedou** [comment]
BTW, I could not make your PR work.

**Comment by guedou** [comment]
@m-chichikalov my mistake ! The example is making the board blink nicely =)

**Comment by guedou** [comment]
Awesome. Thanks a lot!

**Pull request merged**
