### PR TITLE
BluePill F103C8 support

### PR DESCRIPTION
**Pull request by zgoda**
Board definition for BLUEPILL_F103C8 mbed-lib target.

### CODE REVIEW

**Comment by ivankravets** [comment]
Could you rename `vendor` to `Generic`? First letter in upper case. Thanks

**Comment by ivankravets** [comment]
Thanks!

**Comment by zgoda** [comment]
Please note this board requires new build system and will be fully usable with upcoming PlatformIO 3.0.

**Comment by ivankravets** [comment]
Did you test new build system for mbed with your projects?

**Comment by zgoda** [comment]
There was no problems with couple of STM32 based boards that are already supported including STM32F0 discovery and Nucleo F103RB.

**Comment by ivankravets** [comment]
Thanks for the report. We will merge new builder to `develop` branch today.

**Pull request merged**
