### PR TITLE
Add support for LoRa E5 Dev Board

### LINKED ISSUE #596: Board support request: LoRa E5 Dev Board / STM32WLE5JC
[This](https://www.seeedstudio.com/LoRa-E5-Dev-Kit-p-4868.html) is the board/mcu I am looking to add support for, which is very similar to #543. 

I have created this board json called `lora_wle5jc.json` that may work, I don't have a board on-hand just yet to test it yet and putting it in `~/.platformio/boards` didn't let it show up in PlatformIO. I don't know of any frameworks that currently support it, but that is okay for what I am hoping to use it for (just bare-metal) (if a framework is required, please let me know). As well, I am not sure what upload protocols it supports just yet.
 
```json
{
  "build": {
    "core": "stm32",
    "cpu": "cortex-m4",
    "extra_flags": "-DSTM32WLxx -DSTM32WLE5xx",
    "f_cpu": "48000000L",
    "framework_extra_flags": {
      "arduino": "-DUSE_CM4_STARTUP_FILE"
    },
    "mcu": "stm32wle5jc",
    "product_line": "STM32WLE5xx",
    "variant": "STM32WLxx/WL54JCI_WL55JCI_WLE5JC"
  },
  "debug": {
    "default_tools": [
      "stlink"
    ],
    "jlink_device": "STM32WLE5JC",
    "onboard_tools": [
      "stlink"
    ],
    "openocd_target": "stm32wlx",
    "svd_path": "STM32WLE5_CM4.svd"
  },
  "frameworks": [
  ],
  "name": "LoRa E5 Dev Board",
  "upload": {
    "maximum_ram_size": 65536,
    "maximum_size": 262144,
    "protocol": "stlink",
    "protocols": [
      "jlink",
      "cmsis-dap",
      "stlink",
      "mbed"
    ]
  },
  "url": "https://www.seeedstudio.com/LoRa-E5-Dev-Kit-p-4868.html",
  "vendor": "Seeed"
}
```

The SVD is available [here](https://github.com/fullyautomated/st-svd/blob/main/STM32WLE5_CM4.svd).

### PR DESCRIPTION
**Pull request by nobodywasishere**
Closes #596. Can be squashed.

### CODE REVIEW

**Comment by egnor** [comment]
I am excited for this change! Anyone we need to ping to take a look?

**Comment by si2w** [comment]
I tried to use the arduino framework on the board. I added arduino in the frameworks :
```
"frameworks": [
    "arduino",
	  "cmsis",
    "stm32cube",
    "zephyr"
  ],
```
But it seems that some files are missing : 
<command-line>: fatal error: variant_LORA_E5_DEV_BOARD.h: No such file or directory

Could you help ? 

Thanks

**Comment by nobodywasishere** [comment]
For arduino, it looks like there needs to be board specific files added to the stm32duino framework, for example, like the other ones listed [here](https://github.com/stm32duino/Arduino_Core_STM32/tree/main/variants/STM32WLxx).

**Comment by si2w** [comment]
you mean, just copy the directory or adapt them to the lora-e5-dev-board ? If I need to adapt the files, are you aware of a tutorial to do so ? Thanks for your quick response

**Comment by valeros** [comment]
Thanks for the PR, merged.

**Comment by si2w** [comment]
Thanks for the merge

**Pull request merged**
