### PR TITLE
Support Arduino Portenta H7: https://www.arduino.cc/pro/hardware/prod…

### PR DESCRIPTION
**Pull request by long-pham**
Tested on my Arduino Portenta H7, MacOS Catalina 
Thanks to the help of [MaxgerHardt](https://community.platformio.org/u/maxgerhardt). Here's our discussion on the forum
https://community.platformio.org/t/platformio-supports-arduino-portenta-h7/19062

### CODE REVIEW

**Comment by maxgerhardt** [comment]
@valeros FYI the package name `framework-arduino-nrf52-mbedos` is kind of a misnomer here -- initially only the Nano33BLE board used it, but now that exact core (https://github.com/arduino/ArduinoCore-mbed) is also used the STM32H7 (Cortex M7 + H7) based Portenta H7 board, based on mbed-os. Should maybe be renamed if platform-ststm32 supports the Portenta H7 now too with that Arduino core.

**Comment by maxgerhardt** [comment]
An outstanding ToDo in this PR would be to allow an upload to the M4 core too, but for that the dfu-util must be given the `-a1` switch (interface number 1), but it's currently hardcoded to `-a0` and the PR doesn't address that yet. 

https://github.com/platformio/platform-ststm32/blob/2f2cc6115e78eefa8bc31d860309ccf95779dd4e/builder/main.py#L190-L196

(See discussion in forum thread)

**Comment by long-pham** [comment]
> An outstanding ToDo in this PR would be to allow an upload to the M4 core too, but for that the dfu-util must be given the `-a1` switch (interface number 1), but it's currently hardcoded to `-a0` and the PR doesn't address that yet.

The PR works with both cores in my arduino Portenta H7 board.
I'm not sure what `-a` means. But the Arduino IDE uses the same  `-a0` for both the M7 and M4 core. :)

**Comment by maxgerhardt** [comment]
You're right, `-a0` is the same for both the M4 and M7 core. I had in mind that the Arduino IDE had different values for those but they are the same

https://github.com/arduino/ArduinoCore-mbed/blob/a2c06d768f5ebb6821ae6505b2032ee58f4ef70d/boards.txt#L91

https://github.com/arduino/ArduinoCore-mbed/blob/a2c06d768f5ebb6821ae6505b2032ee58f4ef70d/boards.txt#L36

Was suspicious of it because the Arduino IDE explicitly makes this a variable (` -a{upload.interface}`) but all the `upload.interface` values are the same in the `boards.txt`. So this should actually work for the M4.

**Comment by hpssjellis** [comment]
@maxgerhardt @long-pham  Great work guys. Is there a time line for this PR getting merged? The Arduino Pro Portenta products just increased by a 3rd shield. This time the 45.99 USD [BreakoutBoard](https://store.arduino.cc/usa/portenta-breakout) a really cool add-on (I have one) but it will cause lots of programming issues that PlatformIO might be able to help with.

portenta-breakout-board

**Comment by maxgerhardt** [comment]
@valeros Please consider looking in this PR for Portenta H7 supoprt :) (might even be easier with the recently updated Arduino-mbedos core.

**Comment by valeros** [comment]
Many thanks for the PR!

**Comment by valeros** [comment]
Would be great if someone could retest compiling and uploading using the upstream version of the platform:
```ini

[env:portenta_h7_m4]
platform = https://github.com/platformio/platform-ststm32.git
framework = arduino
board = portenta_h7_m4
```

**Comment by JLH-94** [comment]
#511 

Just tried to upload to the M7 core with .ini and seems to
fail because of dfu issues ? (but works despite errors in arduino-IDE)

[env:portenta_h7_m7]
platform = ststm32
board = portenta_h7_m7
framework = arduino

**Comment by hpssjellis** [comment]
@valeros  Sorry it took a while to get back to you. I had several issues just getting PlatformIO working on various machines as I havn't used it in about a year.

Anyway, things look good except for the final installation on the Portenta;

Here is my error code:


```
Processing portenta_h7_m7 (platform: ststm32; board: portenta_h7_m7; framework: arduino)
-------------------------------------------------------------------------------------------------------------

Tool Manager: Installing platformio/tool-stm32duino @ ~1.0.1
Downloading  [####################################]  100%
Tool Manager: tool-stm32duino @ 1.0.2 has been installed!
Tool Manager: Installing platformio/tool-openocd @ ~2.1000.0
Downloading  [####################################]  100%
Unpacking  [####################################]  100%
Tool Manager: tool-openocd @ 2.1000.200630 has been installed!
Verbose mode can be enabled via `-v, --verbose` option
CONFIGURATION: https://docs.platformio.org/page/boards/ststm32/portenta_h7_m7.html
PLATFORM: ST STM32 (12.1.0) > Arduino Portenta H7 (M7 core)
HARDWARE: STM32H747XIH6 480MHz, 511.35KB RAM, 768KB Flash
DEBUG: Current (cmsis-dap) External (cmsis-dap, jlink, stlink)
PACKAGES:
 - framework-arduino-mbed 1.3.2
 - tool-dfuutil 1.9.200310
 - tool-openocd 2.1000.200630 (10.0)
 - tool-stm32duino 1.0.2
 - toolchain-gccarmnoneeabi 1.70201.0 (7.2.1)
LDF: Library Dependency Finder -> http://bit.ly/configure-pio-ldf
LDF Modes: Finder ~ chain, Compatibility ~ soft
Found 24 compatible libraries
Scanning dependencies...
No dependencies
Building in release mode
Checking size .pio\build\portenta_h7_m7\firmware.elf
Advanced Memory Usage is available via "PlatformIO Home > Project Inspect"
RAM:   [=         ]  10.5% (used 55176 bytes from 523624 bytes)
Flash: [=         ]  14.5% (used 114264 bytes from 786432 bytes)
Configuring upload protocol...
AVAILABLE: cmsis-dap, dfu, jlink, mbed, stlink
CURRENT: upload_protocol = dfu
Looking for upload port...
Auto-detected: COM28
Uploading .pio\build\portenta_h7_m7\firmware.bin
dfu-util 0.9

Copyright 2005-2009 Weston Schmidt, Harald Welte and OpenMoko Inc.
Copyright 2010-2020 Tormod Volden and Stefan Schmidt
This program is Free Software and has ABSOLUTELY NO WARRANTY
Please report bugs to http://sourceforge.net/p/dfu-util/tickets/

Invalid DFU suffix signature
A valid DFU suffix will be required in a future dfu-util release!!!
No DFU capable USB device available
*** [upload] Error 74
======================================== [FAILED] Took 17.71 seconds ========================================

```

**Comment by maxgerhardt** [comment]
There's been a few bugfixes per (https://github.com/platformio/platform-ststm32/issues/511#issuecomment-811925155) and you need to replace the old `platform = ststm32` value in the `platformio.ini` with

```
platform = https://github.com/platformio/platform-ststm32.git
```
does it work then?

**Comment by hpssjellis** [comment]
@maxgerhardt 

That line causes problems much earlier, but since these are compile problems, not upload issues, they should be the same for you as for me. Here is what I got


```


> Executing task in folder portenta-m7: C:\Users\jeremy.ellis\.platformio\penv\Scripts\platformio.exe run <

Processing portenta_h7_m7 (platform: https://github.com/platformio/platform-ststm32.git; board: portenta_h7_m7; framework: arduino)
-------------------------------------------------------------------------------------------------------------
Platform Manager: Installing git+https://github.com/platformio/platform-ststm32.git
Error: Traceback (most recent call last):
  File "c:\users\jeremy.ellis\.platformio\penv\lib\site-packages\platformio\commands\run\processor.py", line 
70, in process
    p = PlatformFactory.new(self.options["platform"])
  File "c:\users\jeremy.ellis\.platformio\penv\lib\site-packages\platformio\platform\factory.py", line 54, in new
    raise UnknownPlatform(pkg_or_spec)
platformio.platform.exception.UnknownPlatform: Unknown development platform 'https://github.com/platformio/platform-ststm32.git'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\jeremy.ellis\.platformio\penv\lib\site-packages\platformio\__main__.py", line 109, in main  
    cli()  # pylint: disable=no-value-for-parameter
  File "c:\users\jeremy.ellis\.platformio\penv\lib\site-packages\click\core.py", line 829, in __call__       
    return self.main(*args, **kwargs)
  File "c:\users\jeremy.ellis\.platformio\penv\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "c:\users\jeremy.ellis\.platformio\penv\lib\site-packages\platformio\commands\__init__.py", line 44, in invoke
    return super(PlatformioCLI, self).invoke(ctx)
  File "c:\users\jeremy.ellis\.platformio\penv\lib\site-packages\click\core.py", line 1259, in invoke        
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\jeremy.ellis\.platformio\penv\lib\site-packages\click\core.py", line 1066, in invoke        
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\jeremy.ellis\.platformio\penv\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "c:\users\jeremy.ellis\.platformio\penv\lib\site-packages\click\decorators.py", line 21, in new_func  
    return f(get_current_context(), *args, **kwargs)
  File "c:\users\jeremy.ellis\.platformio\penv\lib\site-packages\platformio\commands\run\command.py", line 133, in cli
    process_env(
  File "c:\users\jeremy.ellis\.platformio\penv\lib\site-packages\platformio\commands\run\command.py", line 175, in process_env
    result = {"env": name, "duration": time(), "succeeded": ep.process()}
  File "c:\users\jeremy.ellis\.platformio\penv\lib\site-packages\platformio\commands\run\processor.py", line 
72, in process
    self.cmd_ctx.invoke(
  File "c:\users\jeremy.ellis\.platformio\penv\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "c:\users\jeremy.ellis\.platformio\penv\lib\site-packages\platformio\commands\platform.py", line 325, 
in platform_install
    pkg = pm.install(
  File "c:\users\jeremy.ellis\.platformio\penv\lib\site-packages\platformio\package\manager\platform.py", line 51, in install
    pkg = super(PlatformPackageManager, self).install(
  File "c:\users\jeremy.ellis\.platformio\penv\lib\site-packages\platformio\package\manager\_install.py", line 48, in install
    pkg = self._install(
  File "c:\users\jeremy.ellis\.platformio\penv\lib\site-packages\platformio\package\manager\_install.py", line 97, in _install
    pkg = self.install_from_url(spec.url, spec, silent=silent)
  File "c:\users\jeremy.ellis\.platformio\penv\lib\site-packages\platformio\package\manager\_install.py", line 141, in install_from_url
    vcs = VCSClientFactory.new(tmp_dir, url)
  File "c:\users\jeremy.ellis\.platformio\penv\lib\site-packages\platformio\package\vcsclient.py", line 54, in new
    obj = getattr(sys.modules[__name__], "%sClient" % type_.title())(
  File "c:\users\jeremy.ellis\.platformio\penv\lib\site-packages\platformio\package\vcsclient.py", line 137, 
in __init__
    self.configure()
  File "c:\users\jeremy.ellis\.platformio\penv\lib\site-packages\platformio\package\vcsclient.py", line 146, 
in configure
    result = proc.exec_command([cls.command, "--exec-path"])
  File "c:\users\jeremy.ellis\.platformio\penv\lib\site-packages\platformio\proc.py", line 117, in exec_command
    p = subprocess.Popen(*args, **kwargs)
  File "C:\Python39\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Python39\lib\subprocess.py", line 1420, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

============================================================


```

**Comment by maxgerhardt** [comment]
Looks like it failed to pull the new platform code via git because you don't have git installed? What happens after installing scm.com/downloads and restarting VSCode?On Apr 2, 2021 00:09, Jeremy Ellis ***@***.***> wrote:
@maxgerhardt
That line causes problems much earlier, but since these are compile problems, not upload issues, they should be the same for you as for me. Here is what I got


> Executing task in folder portenta-m7: C:\Users\jeremy.ellis\.platformio\penv\Scripts\platformio.exe run <

Processing portenta_h7_m7 (platform: https://github.com/platformio/platform-ststm32.git; board: portenta_h7_m7; framework: arduino)
-------------------------------------------------------------------------------------------------------------
Platform Manager: Installing git+https://github.com/platformio/platform-ststm32.git
Error: Traceback (most recent call last):
  File "c:\users\jeremy.ellis\.platformio\penv\lib\site-packages\platformio\commands\run\processor.py", line 
70, in process
    p = PlatformFactory.new(self.options["platform"])
  File "c:\users\jeremy.ellis\.platformio\penv\lib\site-packages\platformio\platform\factory.py", line 54, in new
    raise UnknownPlatform(pkg_or_spec)
platformio.platform.exception.UnknownPlatform: Unknown development platform 'https://github.com/platformio/platform-ststm32.git'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\jeremy.ellis\.platformio\penv\lib\site-packages\platformio\__main__.py", line 109, in main  
    cli()  # pylint: disable=no-value-for-parameter
  File "c:\users\jeremy.ellis\.platformio\penv\lib\site-packages\click\core.py", line 829, in __call__       
    return self.main(*args, **kwargs)
  File "c:\users\jeremy.ellis\.platformio\penv\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "c:\users\jeremy.ellis\.platformio\penv\lib\site-packages\platformio\commands\__init__.py", line 44, in invoke
    return super(PlatformioCLI, self).invoke(ctx)
  File "c:\users\jeremy.ellis\.platformio\penv\lib\site-packages\click\core.py", line 1259, in invoke        
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\jeremy.ellis\.platformio\penv\lib\site-packages\click\core.py", line 1066, in invoke        
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\jeremy.ellis\.platformio\penv\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "c:\users\jeremy.ellis\.platformio\penv\lib\site-packages\click\decorators.py", line 21, in new_func  
    return f(get_current_context(), *args, **kwargs)
  File "c:\users\jeremy.ellis\.platformio\penv\lib\site-packages\platformio\commands\run\command.py", line 133, in cli
    process_env(
  File "c:\users\jeremy.ellis\.platformio\penv\lib\site-packages\platformio\commands\run\command.py", line 175, in process_env
    result = {"env": name, "duration": time(), "succeeded": ep.process()}
  File "c:\users\jeremy.ellis\.platformio\penv\lib\site-packages\platformio\commands\run\processor.py", line 
72, in process
    self.cmd_ctx.invoke(
  File "c:\users\jeremy.ellis\.platformio\penv\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "c:\users\jeremy.ellis\.platformio\penv\lib\site-packages\platformio\commands\platform.py", line 325, 
in platform_install
    pkg = pm.install(
  File "c:\users\jeremy.ellis\.platformio\penv\lib\site-packages\platformio\package\manager\platform.py", line 51, in install
    pkg = super(PlatformPackageManager, self).install(
  File "c:\users\jeremy.ellis\.platformio\penv\lib\site-packages\platformio\package\manager\_install.py", line 48, in install
    pkg = self._install(
  File "c:\users\jeremy.ellis\.platformio\penv\lib\site-packages\platformio\package\manager\_install.py", line 97, in _install
    pkg = self.install_from_url(spec.url, spec, silent=silent)
  File "c:\users\jeremy.ellis\.platformio\penv\lib\site-packages\platformio\package\manager\_install.py", line 141, in install_from_url
    vcs = VCSClientFactory.new(tmp_dir, url)
  File "c:\users\jeremy.ellis\.platformio\penv\lib\site-packages\platformio\package\vcsclient.py", line 54, in new
    obj = getattr(sys.modules[__name__], "%sClient" % type_.title())(
  File "c:\users\jeremy.ellis\.platformio\penv\lib\site-packages\platformio\package\vcsclient.py", line 137, 
in __init__
    self.configure()
  File "c:\users\jeremy.ellis\.platformio\penv\lib\site-packages\platformio\package\vcsclient.py", line 146, 
in configure
    result = proc.exec_command([cls.command, "--exec-path"])
  File "c:\users\jeremy.ellis\.platformio\penv\lib\site-packages\platformio\proc.py", line 117, in exec_command
    p = subprocess.Popen(*args, **kwargs)
  File "C:\Python39\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Python39\lib\subprocess.py", line 1420, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

============================================================

**Comment by hpssjellis** [comment]
Sweet. That works great, I have a ton of programs to test. Thank you so much. 
I just purchased a class sets of the Portenta and accessories, so to have it working with PlatformIO is a huge deal. Please post when this new version is live, I will be tweeting about it. @rocksetta.  
😀

**Pull request merged**
