### PR TITLE
Add board ST-Nucleo-L432KC for mbed framework

### LINKED ISSUE #3: Add support for STM32  Nucleo board - L432KC (and ST Nucleo L011K4)
It would be great to have platformio support for the  [Nucleo board (L432KC)](https://developer.mbed.org/platforms/ST-Nucleo-L432KC/). 
At least a schematic of how to add new boards of the same family would be really helpful.

The other boards of the same Nucleo family that are supported are listed below:
1. ST Nucleo F303K8
2. ST Nucleo F031K6 
3. ST Nucleo F042K6
4. ST Nucleo L031K6 

Also another missing one from the same family- ST Nucleo L011K4

Thanks 

Chandra

### PR DESCRIPTION
**Pull request by mcprakash**
@ivankravets 
 
I really want to add this board and start using it. Please let me know if I need to add some more configurations. 

This PR closes #3

Best

Chandra

### CODE REVIEW

**Comment by ivankravets** [comment]
Did you test it locally? Does it work with current ARM mbed framework?

**Comment by mcprakash** [comment]
@ivankravets I am getting this issue [#108](https://github.com/platformio/platformio-atom-ide/issues/108) with local compiling. Restarting by deleting ~/.atom folder does not fix this issue for me.

**Comment by ivankravets** [comment]
Looks that you have broken board's config. Please open IDE Terminal and run `pio boards`. Do you see any errors?

**Comment by mcprakash** [comment]
@ivankravets PFA a working video of the same

[vid_exc_1.zip](https://github.com/platformio/platform-ststm32/files/470891/vid_exc_1.zip)


Also, could you merge the branch with the master. 

Thanks 

Chandra

**Comment by ivankravets** [comment]
Thanks a lot!

**Pull request merged**
