### PR TITLE
Support arduino for nucleo_h753zi

### PR DESCRIPTION
**Pull request by asukiaaa**
nucleo_h753zi is supported from arduino core stm32 2.7.0  so I want you to support it.
https://github.com/stm32duino/Arduino_Core_STM32/commit/0fb3eff98c4d64c57acefb2ebee29fd0911b40f2

### CODE REVIEW

**Comment by maxgerhardt** [comment]
CC @valeros, another user has ran into this in https://community.platformio.org/t/arduino-framework-for-st-nucleo-h753zi/41466

**Comment by valeros** [comment]
Many thanks for the PR, merged.

**Comment by asukiaaa** [comment]
Thank you for merging but do I need someone's request to check by you?

**Comment by valeros** [comment]
> Thank you for merging but do I need someone's request to be checked by you?

No, we usually review Arduino-related changes when integrating a new version of the Arduino core. Your PR were added just after we released support for core v2.7, so it took a bit of time. Coincidentally, @maxgerhardt pinged just in time when a new v2.8.0 was released.

**Comment by asukiaaa** [comment]
Thank you for answering but really?
Other PR that mention about board supported from 2.7 was merged in few days.
https://github.com/platformio/platform-ststm32/pull/773

**Comment by valeros** [comment]
As I said, usually the PR are reviewed in synch with the Arduino core update, if a similar PR was merged is rather an exception that a rule.

**Comment by asukiaaa** [comment]
I see that the PR was exception for the rule.

**Pull request merged**
