### PR TITLE
feat:add board support for SparkFun MicroMod STM32

### PR DESCRIPTION
**Pull request by bsatrom**

### CODE REVIEW

**Comment by bsatrom** [comment]
@valeros 🤦 yep, you are correct. I will take care of that first and let you know when it's done.

**Comment by bsatrom** [comment]
PR submitted here: https://github.com/stm32duino/Arduino_Core_STM32/pull/1987

**Comment by bsatrom** [comment]
@valeros PR above is approved and set to merge pending CI results. Slated for the 2.6.0 release.

**Comment by diplodocuslongus** [comment]
@bsatrom @valeros hi, so it seems the current version of platform-ststm32 still doesn't support sparkfun micromod stm32f405 chips, is there any issue regarding Brandon's work to be merged here?
Sparkfun micromod STM32 boards are supported in:
https://github.com/stm32duino/Arduino_Core_STM32#sparkfun-boards

Brandon, I've tried your fork with the following setting in my platformio.ini:
```
platform = https://github.com/bsatrom/platform-ststm32.git
board = sparkfun_micromod_f405
framework = arduino

```
But a simple blink example build fails by complaining it can't find `variant_SPARKFUN_MICROMOD_F405.h`. Is there anything else I need to install?

**Comment by bsatrom** [comment]
Hey @diplodocuslongus I suspect that there needs to be an additional change to this PR to support Arduino core 2.6.0, see [here](https://github.com/platformio/platform-ststm32/commit/0e12ce35bc05eab6b20b5de8303abd073f4ea442) for the 2.5.0 bump. I'll update this, but if you want to try yourself, open `platform.json` and change line 195 to 

```
"version": "~4.20600.0"
```

**Comment by valeros** [comment]
Thanks for the PR, merged.

**Pull request merged**
