### PR TITLE
Added Maple bootloader revision change support

### PR DESCRIPTION
**Pull request by ubis**
By default, bootloader revision is newer(2). To use older(rev 1), platformio.ini should have option:

> upload_flags = 1

### CODE REVIEW

**Comment by ivankravets** [comment]
Thanks! :)

1. Have you tested it? I see that you use `upload_flags`, but this value will be appended to the end after all your manipulation: https://github.com/platformio/platformio/blob/develop/platformio/builder/main.py#L138
2. Very strange PR technically. 10 conflicted commits with 2 new. Could you delete previous `DFU_fixes` branch, pull updates from remote and create new PR?
3. Please remove debug print https://github.com/platformio/platform-ststm32/pull/12/files#diff-7bf8a7e6a6e69b354a3d3e106cc0cbacR166
4. `usbRev` - is this positional argument? Or it can be in any place?
P.S: Please sorry, but for us is very important code quality :(

**Comment by ubis** [comment]
Yeah, my bad - I just printed it, to see if it changes bootloader revision. Any ideas how I can do that? With a custom platformio.ini variable probably?

As for PR, well I tried to sync my work and I had a few conflicts. I've fixed them and pushed commit to fork and made a new branch(because I didn't wanted to have my "update fork" commit in PR) and did some changes. So I should push my changes into develop branch and then make a PR, compare with it?

As for `usbRev ` variable, i'm not sure, but I think it's positional.

Well, sorry for writing such code, i'm kinda newbie in Python and i'm more concerned about that linking problem(I think I found solution already), so I wasn't taking attention to these changes..

**Comment by ivankravets** [comment]
Thanks, I self-assigned issue https://github.com/platformio/platform-ststm32/issues/9

**Comment by ivankravets** [comment]
Please help us with 
* https://github.com/platformio/platform-ststm32/issues/10
* https://github.com/platformio/platform-ststm32/issues/11

If you need some help with PlatformIO Build System, please contact me.

**Pull request closed without merging**
