### PR TITLE
Add support for ST Nucleo G491RE

### PR DESCRIPTION
**Pull request by gudnimg**
Closes https://github.com/platformio/platform-ststm32/issues/496

### CODE REVIEW

**Comment by gudnimg** [comment]
The check failure is unrelated to the code changes. Not sure what could cause this:

image

**Comment by jeremiahrose** [comment]
Any progress on G491RE support? What's the blocker for merging this PR?

**Comment by valeros** [comment]
@jeremiahrose there is no support for this board in the official Arduino core for ST STM32.

**Comment by jeremiahrose** [comment]
@valeros thanks for the info. We do want to support G491RE eventually though, right? If that's true then maybe we should reopen this issue and mark it as blocked for the time being?

I just took a look at https://github.com/stm32duino/Arduino_Core_STM32/issues/722 and it looks like they do plan to include the G491RE eventually, and it's on their todo list. Unless I'm misunderstanding something?

**Comment by valeros** [comment]
> it looks like they do plan to include the G491RE eventually, and it's on their todo list. 

I'm not sure why this board hasn't been added yet, they're probably waiting for a PR with proper implementation from someone interested in this board.

**Pull request closed without merging**
