### PR TITLE
STM32 arduino core changes

### PR DESCRIPTION
**Pull request by ubis**

### CODE REVIEW

**Comment by ivankravets** [comment]
Thanks! 😊 

Do you have any ideas as for the issues? https://travis-ci.org/platformio/platform-ststm32/jobs/445270406

**Comment by ivankravets** [comment]
Do we have Arduino compatible boards which are not supported in official core but presented in legacy? We should handle this moment automatically. Otherwise, someone will create a project for board A which has declared "framework: arduino" and it will not work.

**Comment by ubis** [comment]
Hmm I overlooked. At the moment we have multiple boards with the same mcu. So let's say only ST Nucleo F103RB is supported by STM32core and we have `genericF103RB103; nucleo_f103rb; maple`. Variant name, used in STM32 core is generated from board name, so these two with the same mcu won't work.
Since boards are different, but their mcu is same, we could do a remap for each mcu.

Seems like that's why I left to use legacy core with F103/F407 families.

**Comment by ivankravets** [comment]
It seems that I have a good solution here. How about to check if board's `build.variant` exists in STM32Core then use it, otherwise, the legacy will be used? 

P.S: I've just only noticed that we do use valid `variant` in board's manifest. We use it everywhere for Arduino-compatible boards. How is difficult to switch `build.variant` of each board to it's real value?

**Comment by ubis** [comment]
Sorry, I had been busy these days.
Well, first we should decide either we should support the exact boards or different boards with similar mcu's. And what do you mean by
> `build.variant` real value

As for now, variant in manifest is mcu's family name, and libOpenCM3 or other frameworks use it as well.

**Comment by ivankravets** [comment]
@valeros could we switch off libopencm3 from "variant" data field? I propose to use this field just for Arduino. Historically, this field belongs to Arduino pinmap/variants.

**Pull request closed without merging**
