### PR TITLE
Arduino support for Nucleo F103RB

### PR DESCRIPTION
**Pull request by DavidPowell**
Support for the Nucleo F103RB is already included in the stm32duino project. All that is required is to provide a separate json file for the Arduino framework, because settings such as `core` and `ldscript` need to be modified.

Solution is based somewhat on the `bluepill_f103c8`. However, as separate `boards/arduino` subfolder was created, to facilitate adding other boards supported by stm32duino just by adding a modified copy of their json file.

### CODE REVIEW

**Comment by ivankravets** [comment]
Thanks a lot for your PR!

We don't need a new manifest for this board. You can use `boards/nucleo_f103rb.json` and extend it with required information. Please note that we don't use `build` section from this manifest, you can specify here Arduino related settings.

**Comment by DavidPowell** [comment]
Okay, I didn't realise that the `build` section is Arduino-specific. PR has been simplified to just modify the existing manifest. I confirmed that both Arduino and mbed blink examples still work as expected. This is important since incorrect link settings mean that the code will still compile, and pass integration checks, but will not produce correct output.

**Comment by DavidPowell** [comment]
@ivankravets - Actually, it seems that the STM32 HAL examples do use the `build` section of the manifest. My changes broke the `stm32cube-hal-blink` example. I have pushed a fix, but it will have the side-effect that some Arduino-specific `#define`s will appear when compiling under the HAL.

**Comment by ubis** [comment]
This should be available since #84 
Could @DavidPowell test it by installing develop branch?

**Comment by DavidPowell** [comment]
@ubis I updated my platform ststm32 to develop, and tried the arduino, cubemx-hal and mbed blink examples on the Nucleo F103RB. 

The Arduino blink example works fine (after modifying it to use the correct LED output pin).

The cubemx-hal example produces no output (however I think this example has always been problematic as it does not have chip specific code to setup clocks etc).

The mbed example failed to even compile, with an error `src\main.cpp:1:18: fatal error: mbed.h: No such file or directory`.

This is preceded by a warning `Warning: Ignoring missing SConscript 'C:\Users\dap124\.platformio\platforms\platform-ststm32\builder\frameworks\mbed\mbed.py'
File "C:\Users\dap124\.platformio\penv\lib\site-packages\platformio\builder\tools\platformio.py", line 264, in BuildFrameworks`

I can confirm that `mbed.py` is present, I'm not sure why it's being ignored.

**Comment by ubis** [comment]
Since it's working with Arduino framework, I believe this PR can be closed.
Unfortunately, I can't reproduce your error with mbed framework. 
Can you delete your `.platformio` folder and try again? Also create a new issue if you are still getting any errors with mbed framework.

**Comment by DavidPowell** [comment]
@ubis Problem fixed, it turns out I should have referenced git repository for devel version instead of cloning it (which doesn't pull in submodules)

This pull request is now made redundant by #84.

**Pull request closed without merging**
